---
- name: Testing Galaxy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infra.ah_configuration
  vars:
    ah_hostname: http://10.242.42.169:8002
    ah_username: admin
    ah_password: admin
    ah_path_prefix: automation-hub
    ah_validate_certs: false
    ah_configuration_ee_registry_sync_async_delay: 5

    ah_namespaces:
      - name: community_test
  tasks:
    - name: Create namespace
      ansible.builtin.include_role:
        name: namespace

    - name: Rename namespace
      ansible.builtin.include_role:
        name: namespace
      vars:
        ah_namespaces:
          - name: community_test
            new_name: community_test_renamed

    - name: Delete renamed namespace
      ansible.builtin.include_role:
        name: namespace
      vars:
        ah_namespaces:
          - name: community_test_renamed
            state: absent
...
