---
# Create AH repository
- name: Update Certified repository
  ah_repository:
    name:                 "rh-certified"
    url:                  "{{ ah_repository_certified['url'] | default('https://cloud.redhat.com/api/automation-hub/') }}"
    auth_url:             "{{ ah_repository_certified['auth_url'] | default('https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token') }}"
    token:                "{{ ah_repository_certified['token'] | default(omit) }}"
    username:             "{{ ah_repository_certified['username'] | default(omit) }}"
    password:             "{{ ah_repository_certified['password'] | default(omit) }}"
    download_concurrency: "{{ ah_repository_certified['download_concurrency'] | default(10) }}"
    proxy_url:            "{{ proxy_url | default(omit) }}"
    proxy_username:       "{{ proxy_username | default(omit) }}"
    proxy_password:       "{{ proxy_password | default(omit) }}"
  no_log: "{{ ah_configuration_repository_secure_logging }}"
  when: ah_repository_certified is defined

- name: Update Community repository
  ah_repository:
    name:                 "community"
    url:                  "{{ ah_repository_community['url'] | default('https://galaxy.ansible.com/api/') }}"
    username:             "{{ ah_repository_community['username'] | default(omit) }}"
    password:             "{{ ah_repository_community['password'] | default(omit) }}"
    requirements:         "{{ ah_repository_community['requirements'] | default(omit) }}"
    requirements_file:    "{{ ah_repository_community['requirements_file'] | default(omit }}"
    download_concurrency: "{{ ah_repository_community['download_concurrency'] | default(10) }}"
    proxy_url:            "{{ proxy_url | default(omit) }}"
    proxy_username:       "{{ proxy_username | default(omit) }}"
    proxy_password:       "{{ proxy_password | default(omit) }}"
  no_log: "{{ ah_configuration_repository_secure_logging }}"
  when: ah_repository_community is defined
...
