---
name: Test roles and modules - dab_jwt
on: [push, pull_request_target]

jobs:
  ci_dab_jwt:
    strategy:
      fail-fast: false
      matrix:
        galaxy_ng_version:
          - master
    uses: "./.github/workflows/ci_dab_jwt_versioned.yml"
    with:
      galaxy_ng_version: ${{ matrix.galaxy_ng_version }}
      gh_ref: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets:
      redhat_catalog_username: ${{ secrets.REDHAT_CATALOG_USERNAME }}
      redhat_catalog_password: ${{ secrets.REDHAT_CATALOG_PASSWORD }}
