---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        galaxy_ng_version:
          - stable-4.4
          - stable-4.5
          - stable-4.6
          # - master disabled until build issue resolved
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      galaxy_ng_version: ${{ matrix.galaxy_ng_version }}
    secrets:
      redhat_catalog_username: ${{ secrets.REDHAT_CATALOG_USERNAME }}
      redhat_catalog_password: ${{ secrets.REDHAT_CATALOG_PASSWORD }}
  release:
    needs:
      - ci_standalone
    uses: "redhat-cop/ansible_collections_tooling/.github/workflows/release_pipeline_dual.yml@main"
    with:
      # Galaxy Publish
      collection_namespace_1: infra
      collection_name_1: ah_configuration
      publish_url_collection_1: https://galaxy.ansible.com
      galaxy_publish_1: true
      ah_publish_1: false
      # CRC Publish
      collection_namespace_2: infra
      collection_name_2: ah_configuration
      publish_url_collection_2: https://cloud.redhat.com/api/automation-hub/
      galaxy_publish_2: false
      ah_publish_2: true
      collection_version: ${{ github.ref_name }}
      collection_repo: https://github.com/ansible/galaxy_collection
      quay_username: redhat_cop
      matrix_message: This Ansible collection allows for easy interaction with an Galaxy NG or Ansible Automation Hub via Ansible modules and roles.
    secrets:
      collection_api_key_1: ${{ secrets.GALAXY_INFRA_KEY }}
      collection_api_key_2: ${{ secrets.CRC_PUBLISH_KEY }}
      git_token: ${{ secrets.GITHUB_TOKEN }}
      quay_token: ${{ secrets.quay_token }}
      matrix_token: ${{ secrets.matrix_token }}

...
